-- Migration: 007_add_complete_product_catalog.sql
-- Catálogo sincronizado conforme documento DOCX

-- Garantir unicidade para UPSERT
DELETE FROM public.products a USING public.products b WHERE a.id < b.id AND a.name = b.name;
CREATE UNIQUE INDEX IF NOT EXISTS products_name_key ON public.products (name);

INSERT INTO public.products (name, type, description, in_stock, price, image_url)
VALUES
('EXTINTOR PÓ QUÍMICO BC - 4 KG', 'Extintor', 'Agente Químico : PQS. Carga: 4 Kg. Capacidade : 20 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-4-kg.png'),
('EXTINTOR PÓ QUÍMICO BC - 8 KG', 'Extintor', 'Agente Químico : PQS. Carga: 8 Kg. Capacidade : 30 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-8-kg.png'),
('EXTINTOR PÓ QUÍMICO BC - 6 KG', 'Extintor', 'Agente Químico : PQS. Carga: 6 Kg. Capacidade : 20 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-6-kg.png'),
('EXTINTOR PÓ QUÍMICO BC - 12 KG', 'Extintor', 'Agente Químico : PQS. Carga: 12 Kg. Capacidade : 40 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-12-kg.png'),
('EXTINTOR PÓ QUÍMICO BC - 50 KG', 'Extintor', 'Agente Químico : PQS. Carga: 50 Kg. Capacidade : 80 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-50-kg.png'),
('EXTINTOR CO² BC - 4 KG', 'Extintor', 'Agente Químico : CO². Carga: 4 Kg. Capacidade : 5 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-co-bc-4-kg.png'),
('EXTINTOR CO² BC - 6 KG', 'Extintor', 'Agente Químico : CO². Carga: 6 Kg. Capacidade : 5 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-co-bc-6-kg.png'),
('EXTINTOR ÁGUA CLASSE A - 10 L', 'Extintor', 'Agente Químico : ÁGUA. Carga: 10 L. Capacidade : 2 A. Classe de fogo : A. Garantia : 1 Ano.', true, 0, '/products/extintor-agua-classe-a-10-l.png'),
('EXTINTOR ESPUMA MECÂNICA AB - 10 L', 'Extintor', 'Agente Químico : ESPUMA MECÂNICA. Carga: 10 L. Capacidade : 2 A. Classe de fogo : A. Garantia : 1 Ano.', true, 0, '/products/extintor-espuma-mecanica-ab-10-l.png'),
('EXTINTOR PÓ QUÍMICO ABC - 0,900 KG (FIAT)', 'Extintor', 'Agente Químico : PQS. Carga: 0,900 Kg. Capacidade : 1 A - 5 B:C. Classe de fogo : ABC. Garantia : 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-0-900-kg-fiat.png'),
('EXTINTOR PÓ QUÍMICO ABC - 2 KG (1A-10BC)', 'Extintor', 'Agente Químico : PQS. Carga: 2 Kg. Capacidade : 1 A - 10 B:C. Classe de fogo : ABC. Garantia : 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-2-kg-1a-10bc.png'),
('EXTINTOR PÓ QUÍMICO ABC - 2 KG (2A-20BC)', 'Extintor', 'Agente Químico : PQS. Carga: 2 Kg. Capacidade : 2 A - 20 B:C. Classe de fogo : ABC. Garantia : 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-2-kg-2a-20bc.png'),
('EXTINTOR PÓ QUÍMICO ABC - 4 KG', 'Extintor', 'Agente Químico : PQS. Carga: 4 Kg. Capacidade : 2 A - 20 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-4-kg.png'),
('EXTINTOR PÓ QUÍMICO ABC - 6 KG', 'Extintor', 'Agente Químico : PQS. Carga: 6 Kg. Capacidade : 4 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-6-kg.png'),
('EXTINTOR PÓ QUÍMICO ABC - 8 KG', 'Extintor', 'Agente Químico : PQS. Carga: 8 Kg. Capacidade : 4 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-8-kg.png'),
('EXTINTOR PÓ QUÍMICO ABC - 12 KG', 'Extintor', 'Agente Químico : PQS. Carga: 12 Kg. Capacidade : 6 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-12-kg.png'),
('EXTINTOR PÓ QUÍMICO ABC - 20 KG', 'Extintor', 'Agente Químico : PQS. Carga: 20 Kg. Capacidade : 6 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-abc-20-kg.png'),
('EXTINTOR PÓ QUÍMICO ABC - 30 KG', 'Extintor', 'Agente Químico : PQS. Carga: 30 Kg. Capacidade : 6 A - 80 B:C. Classe de fogo : ABC. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-abc-30-kg.png'),
('PÓ QUÍMICO BC - BICARBONATO DE SÓDIO 95%', 'Agente Extintor', 'Agente Químico : Bicarbonato de Sódio 95%. Embalagem : 50 Kg.', true, 0, '/products/po-quimico-bc-bicarbonato-de-sodio-95.png'),
('PÓ QUÍMICO ABC - MONOFOSFATO DE AMÔNIO 55%', 'Agente Extintor', 'Agente Químico : Monofosfato de Amônio 55%. Embalagem : 50 Kg.', true, 0, '/products/po-quimico-abc-monofosfato-de-amonio-55.png'),
('VÁLVULA M30 COMPLETA', 'Componentes', 'Código: 85281. Válvula completa para extintores de baixa pressão .', true, 0, '/products/valvula-m30-completa.png'),
('PERA M30', 'Acessórios', 'Código: 504 | 68031. Pera para válvula M30.', true, 0, '/products/pera-m30.png'),
('MANÔMETRO 1.0 - CAIXA INOX', 'Acessórios', 'Código: 85271. Manômetro com caixa em inox.', true, 0, '/products/manometro-1-0-caixa-inox.png'),
('BUCHA PLÁSTICA PARA VÁLVULA M30 CURTA', 'Componentes', 'Código: 4317. Bucha plástica para válvula M30 curta com encosto , 5 fios de rosca .', true, 0, '/products/bucha-plastica-para-valvula-m30-curta.png'),
('MOLA CURTA (ALTURA 1,98 CM)', 'Acessórios', 'Código: 3109. Mola curta para válvulas .', true, 0, '/products/mola-curta-altura-1-98-cm.png'),
('VÁLVULA M22', 'Componentes', 'Código: 85881. Válvula M22 para extintores .', true, 0, '/products/valvula-m22.png'),
('ORING GROSSA 26X4 MM PARA VÁLVULA M30', 'Componentes', 'Código: 85341. Oring grossa para vedação de válvula M30.', true, 0, '/products/oring-grossa-26x4-mm-para-valvula-m30.png'),
('MANÔMETRO 1.4 INOX', 'Acessórios', 'Código: 3139. Manômetro com escala 1.4 e caixa inox.', true, 0, '/products/manometro-1-4-inox.png'),
('PINO COMPLETO PARA VÁLVULA M30', 'Componentes', 'Código: 3105. Pino completo para válvula M30 ( arruela em latão + pera + oring de pino ). Medida : 33 mm.', true, 0, '/products/pino-completo-para-valvula-m30.png'),
('MOLA LONGA (ALTURA 4,3 CM)', 'Acessórios', 'Código: 5776. Mola longa para válvulas .', true, 0, '/products/mola-longa-altura-4-3-cm.png'),
('CORDÃO PARA VÁLVULA M30', 'Componentes', 'Código: 73341. Cordão de segurança para válvula M30.', true, 0, '/products/cordao-para-valvula-m30.png'),
('TRAVA PARA VÁLVULA M30', 'Componentes', 'Código: 4357. Trava de segurança para válvula M30.', true, 0, '/products/trava-para-valvula-m30.png'),
('MANGUEIRA PARA EXTINTOR P4/P6/P8 - 500 MM', 'Extintor', 'Código: 85631. Mangueira para extintores P4, P6 e P8 com 500 mm.', true, 0, '/products/mangueira-para-extintor-p4-p6-p8-500-mm.png'),
('MANGUEIRA PARA EXTINTOR P12 - 600 MM', 'Extintor', 'Código: 49. Mangueira para extintor P12 com 600 mm.', true, 0, '/products/mangueira-para-extintor-p12-600-mm.png'),
('MANGUEIRA PARA EXTINTOR AP10L - 600 MM', 'Extintor', 'Código: 85641. Mangueira para extintor AP10L com 600 mm.', true, 0, '/products/mangueira-para-extintor-ap10l-600-mm.png'),
('SIFÃO PLÁSTICO PARA EXTINTOR P4 - 11 MM', 'Extintor', 'Código: 85581. Sifão plástico para extintor P4, 11 mm.', true, 0, '/products/sifao-plastico-para-extintor-p4-11-mm.png'),
('SIFÃO PLÁSTICO PARA EXTINTOR P6 - 460 MM', 'Extintor', 'Código: 85591. Sifão plástico para extintor P6, 460 mm.', true, 0, '/products/sifao-plastico-para-extintor-p6-460-mm.png'),
('SIFÃO PLÁSTICO PARA EXTINTOR P8 - 380 MM', 'Extintor', '', true, 0, '/products/sifao-plastico-para-extintor-p8-380-mm.png'),
('SIFÃO PLÁSTICO PARA EXTINTOR P12/AP10L - 535 MM', 'Extintor', 'Código: 85611. Sifão plástico para extintores P12 e AP10L, 535 mm.', true, 0, '/products/sifao-plastico-para-extintor-p12-ap10l-535-mm.png'),
('CAPA PARA EXTINTORES', 'Extintor', 'Capa protetora para todos os tamanhos de extintores .', true, 0, '/products/capa-para-extintores.png'),
('MANGUEIRA DE INCÊNDIO - TIPO 1, 2 E 3', 'Mangueira', 'Mangueiras de incêndio tipos 1, 2 e 3. Tamanhos : 15, 20, 25 e 30 metros.', true, 0, '/products/mangueira-de-incendio-tipo-1-2-e-3.png'),
('CONJUNTO APAG PARA CO ²', 'Acessórios', 'Código: 279. Conjunto completo para extintores CO².', true, 0, '/products/conjunto-apag-para-co.png'),
('MANGUEIRA CO²', 'Mangueira', 'Código: 53. Mangueira específica para extintores CO².', true, 0, '/products/mangueira-co.png'),
('DIFUSOR PARA CO ² COMPLETO', 'Acessórios', 'Código: 4341. Difusor completo para extintores CO².', true, 0, '/products/difusor-para-co-completo.png'),
('PUNHO PARA CO ²', 'Acessórios', 'Código: 534. Punho para extintores CO².', true, 0, '/products/punho-para-co.png'),
('QUEBRA JATO PARA CO ²', 'Acessórios', 'Código: 535. Quebra jato para extintores CO².', true, 0, '/products/quebra-jato-para-co.png'),
('VÁLVULA PARA CO ² COMPLETA', 'Componentes', 'Código: 479. Válvula completa para extintores CO².', true, 0, '/products/valvula-para-co-completa.png'),
('SIFÃO PARA EXTINTOR CO² - 4 KG', 'Extintor', 'Código: 365. Sifão para extintor CO² de 4 kg.', true, 0, '/products/sifao-para-extintor-co-4-kg.png'),
('SIFÃO PARA EXTINTOR CO² - 6 KG', 'Extintor', 'Código: 368. Sifão para extintor CO² de 6 kg.', true, 0, '/products/sifao-para-extintor-co-6-kg.png'),
('SIFÃO PARA EXTINTOR CO² - 10 KG', 'Extintor', 'Código: 364. Sifão para extintor CO² de 10 kg.', true, 0, '/products/sifao-para-extintor-co-10-kg.png'),
('VÁLVULA ABERTURA LENTA CO²', 'Componentes', 'Código: 1833. Válvula de abertura lenta para extintores CO².', true, 0, '/products/valvula-abertura-lenta-co.png'),
('VÁLVULA M30 COMPLETA ( ESPUMA MECÂNICA )', 'Componentes', 'Código: 85281. Válvula completa para extintores de espuma mecânica 10L.', true, 0, '/products/valvula-m30-completa-espuma-mecanica.png'),
('MANÔMETRO 1.0 - CAIXA INOX ( ESPUMA MECÂNICA )', 'Acessórios', 'Código: 85271. Manômetro com caixa inox para extintores de espuma .', true, 0, '/products/manometro-1-0-caixa-inox-espuma-mecanica.png'),
('MANGUEIRA DE ESPUMA MECÂNICA 600 MM COM DIFUSOR', 'Mangueira', 'Código: 89331. Mangueira para extintor de espuma mecânica com difusor .', true, 0, '/products/mangueira-de-espuma-mecanica-600-mm-com-difusor.png'),
('LÍQUIDO GERADOR DE ESPUMA - LGE 3%', 'Acessórios', 'Código: 1429. Líquido gerador de espuma a 3%.', true, 0, '/products/liquido-gerador-de-espuma-lge-3.png'),
('LÍQUIDO GERADOR DE ESPUMA - LGE 6%', 'Acessórios', 'Código: 1697. Líquido gerador de espuma a 6%.', true, 0, '/products/liquido-gerador-de-espuma-lge-6.png'),
('LÍQUIDO GERADOR DE ESPUMA - LGE 3%-6%', 'Acessórios', 'Código: 4849. Líquido gerador de espuma versátil 3%-6%.', true, 0, '/products/liquido-gerador-de-espuma-lge-3-6.png'),
('MANÔMETRO 1.0 - CAIXA INOX (P2 ABC)', 'Acessórios', 'Código: 85271. Manômetro para extintores P2 ABC.', true, 0, '/products/manometro-1-0-caixa-inox-p2-abc.png'),
('VÁLVULA M-22 COM ROSCA (P2 ABC)', 'Componentes', 'Código: 85881. Válvula M22 com rosca para P2 ABC.', true, 0, '/products/valvula-m-22-com-rosca-p2-abc.png'),
('MANGUEIRA P2 ABC', 'Mangueira', 'Código: 61091. Mangueira específica para extintores P2 ABC.', true, 0, '/products/mangueira-p2-abc.png'),
('VÁLVULA M38 PARA CARRETA - PQS 20 KG', 'Componentes', 'Código: 85551. Válvula M38 para extintor sobre rodas de 20 kg.', true, 0, '/products/valvula-m38-para-carreta-pqs-20-kg.png'),
('VÁLVULA M38 PARA CARRETA - PQS 30 KG', 'Componentes', 'Código: 85561. Válvula M38 para extintor sobre rodas de 30 kg.', true, 0, '/products/valvula-m38-para-carreta-pqs-30-kg.png'),
('VÁLVULA M38 PARA CARRETA - PQS 50 KG', 'Componentes', 'Código: 85571. Válvula M38 para extintor sobre rodas de 50 kg.', true, 0, '/products/valvula-m38-para-carreta-pqs-50-kg.png'),
('MANGUEIRA PARA EXTINTOR CARRETA 30 KG', 'Extintor', 'Código: 5068. Mangueira para extintor sobre rodas de 30 kg.', true, 0, '/products/mangueira-para-extintor-carreta-30-kg.png'),
('MANGUEIRA P20 - 3 METROS', 'Mangueira', 'Código: 85401. Mangueira de 3 metros para extintor de 20 kg.', true, 0, '/products/mangueira-p20-3-metros.png'),
('MANGUEIRA PARA EXTINTOR CARRETA 50 KG', 'Extintor', 'Código: 90971. Mangueira para extintor sobre rodas de 50 kg.', true, 0, '/products/mangueira-para-extintor-carreta-50-kg.png'),
('PISTOLA DE CARRETA - 20 KG', 'Acessórios', 'Código: 85411. Pistola para extintor sobre rodas de 20 kg.', true, 0, '/products/pistola-de-carreta-20-kg.png'),
('ADAPTADOR CARRETA - PQS 30/50 KG', 'Combate a Incêndio', 'Código: 5618. Adaptador para carretas de 30 kg e 50 kg.', true, 0, '/products/adaptador-carreta-pqs-30-50-kg.png'),
('RODA PLÁSTICA PQS 20 KG', 'Acessórios', 'Código: 85421. Roda plástica para extintor sobre rodas de 20 kg.', true, 0, '/products/roda-plastica-pqs-20-kg.png'),
('SUPORTE VEICULAR - MODELO FIAT', 'Suporte', 'Código: 457. Suporte para extintor veicular modelo FIAT.', true, 0, '/products/suporte-veicular-modelo-fiat.png'),
('SUPORTE VEICULAR - MODELO UNIVERSAL', 'Suporte', 'Código: 4459. Suporte para extintor veicular modelo universal.', true, 0, '/products/suporte-veicular-modelo-universal.png'),
('SUPORTE VEICULAR - MODELO P2 ABC', 'Suporte', 'Código: 461. Suporte veicular para extintor P2 ABC.', true, 0, '/products/suporte-veicular-modelo-p2-abc.png'),
('SUPORTE VEICULAR - MODELO P4/P6', 'Suporte', 'Código: 4355. Suporte veicular para extintores P4 e P6.', true, 0, '/products/suporte-veicular-modelo-p4-p6.png'),
('SUPORTE VEICULAR - MODELO P8/P12', 'Suporte', 'Código: 456. Suporte veicular para extintores P8 e P12.', true, 0, '/products/suporte-veicular-modelo-p8-p12.png'),
('SUPORTE PAREDE', 'Suporte', 'Código: 1725. Suporte de parede para extintores .', true, 0, '/products/suporte-parede.png'),
('SUPORTE TRIPÉ DESMONTÁVEL - P4/P6', 'Suporte', 'Código: 65461. Suporte tripé desmontável para extintores P4 e P6.', true, 0, '/products/suporte-tripe-desmontavel-p4-p6.png'),
('SUPORTE TRIPÉ DESMONTÁVEL - P8/P12/AP10', 'Suporte', 'Código: 65471. Suporte tripé desmontável para extintores P8, P12 e AP10.', true, 0, '/products/suporte-tripe-desmontavel-p8-p12-ap10.png'),
('SUPORTE TRIPÉ - P4/P6', 'Suporte', 'Código: 450. Suporte tripé fixo para extintores P4 e P6.', true, 0, '/products/suporte-tripe-p4-p6.png'),
('SUPORTE TRIPÉ - P8/P12/AP10', 'Suporte', 'Código: 454. Suporte tripé fixo para extintores P8, P12 e AP10.', true, 0, '/products/suporte-tripe-p8-p12-ap10.png'),
('SUPORTE TRIPÉ COM HASTE - P4/P6', 'Suporte', 'Código: 676. Suporte tripé com haste para extintores P4 e P6.', true, 0, '/products/suporte-tripe-com-haste-p4-p6.png'),
('SUPORTE TRIPÉ COM HASTE - P8/P12/AP10', 'Suporte', 'Código: 702. Suporte tripé com haste para extintores P8, P12 e AP10.', true, 0, '/products/suporte-tripe-com-haste-p8-p12-ap10.png'),
('SUPORTE SOLO TRIPÉ BICROMATIZADO - P4/P6', 'Suporte', 'Código: 2962. Suporte solo tripé bicromatizado com fixação no solo para P4/P6.', true, 0, '/products/suporte-solo-tripe-bicromatizado-p4-p6.png'),
('SUPORTE SOLO TRIPÉ BICROMATIZADO - P8/P12/AP10', 'Suporte', 'Código: 64631. Suporte solo tripé bicromatizado com fixação no solo para P8/P12/AP10.', true, 0, '/products/suporte-solo-tripe-bicromatizado-p8-p12-ap10.png'),
('SUPORTE SOLO TRIPÉ BICROMATIZADO - CO²', 'Suporte', 'Código: 64631. Suporte solo tripé bicromatizado com fixação no solo para CO ².', true, 0, '/products/suporte-solo-tripe-bicromatizado-co.png'),
('SUPORTE SOLO TRIPÉ CROMADO - P4/P6', 'Suporte', 'Código: 1039. Suporte solo tripé cromado para P4/P6.', true, 0, '/products/suporte-solo-tripe-cromado-p4-p6.png'),
('SUPORTE SOLO TRIPÉ CROMADO - P8/P12/AP10', 'Suporte', 'Código: 1035. Suporte solo tripé cromado para P8/P12/AP10.', true, 0, '/products/suporte-solo-tripe-cromado-p8-p12-ap10.png'),
('SUPORTE SOLO TRIPÉ CROMADO - CO²', 'Suporte', 'Código: 1035. Suporte solo tripé cromado para CO ².', true, 0, '/products/suporte-solo-tripe-cromado-co.png'),
('SUPORTE DE SOLO TRIPÉ DESMONTÁVEL DE POLIETILENO - P4/P6', 'Suporte', 'Código: 77481. Suporte solo tripé desmontável de polietileno de alta densidade para P4/P6.', true, 0, '/products/suporte-de-solo-tripe-desmontavel-de-polietileno-p4-p6.png'),
('SUPORTE DE SOLO TRIPÉ DESMONTÁVEL DE POLIETILENO - P8/P12/AP/EM', 'Suporte', 'Código: 77471. Suporte solo tripé desmontável de polietileno de alta densidade para P8/P12/AP/EM.', true, 0, '/products/suporte-de-solo-tripe-desmontavel-de-polietileno-p8-p12-ap-em.png'),
('SUPORTE DE SOLO TRIPÉ DESMONTÁVEL DE POLIETILENO - CO²', 'Suporte', 'Código: 77471. Suporte solo tripé desmontável de polietileno de alta densidade para CO ².', true, 0, '/products/suporte-de-solo-tripe-desmontavel-de-polietileno-co.png'),
('SUPORTE DE SOLO BATOM - P4/P6', 'Suporte', 'Código: 88671. Suporte de solo tipo " batom " para P4/P6.', true, 0, '/products/suporte-de-solo-batom-p4-p6.png'),
('SUPORTE DE SOLO BATOM - P8/P12/AP/EM', 'Suporte', 'Código: 3900. Suporte de solo tipo " batom " para P8/P12/AP/EM.', true, 0, '/products/suporte-de-solo-batom-p8-p12-ap-em.png'),
('SUPORTE DE SOLO BATOM - CO²', 'Suporte', 'Código: 3900. Suporte de solo tipo " batom " para CO ².', true, 0, '/products/suporte-de-solo-batom-co.png'),
('HASTE PARA SUPORTE TRIPÉ', 'Suporte', 'Código: 69961. Haste para suporte tripé (P4/P6/P8/P12/AP/EM/10L/CO²).', true, 0, '/products/haste-para-suporte-tripe.png'),
('ADAPTADOR STORZ 2.1/2" X 1.1/2"', 'Combate a Incêndio', 'Adaptador Storz 2.1/2" x 1.1/2". Opção Latão ou Alumínio .', true, 0, '/products/adaptador-storz-2-1-2-x-1-1-2.png'),
('REDUTOR STORZ 2.1/2" X 1.1/2"', 'Combate a Incêndio', 'Redutor Storz 2.1/2" x 1.1/2". Opção Latão ou Alumínio .', true, 0, '/products/redutor-storz-2-1-2-x-1-1-2.png'),
('UNIÃO STORZ PARA MANGUEIRA DE INCÊNDIO', 'Mangueira', 'União Storz para conexão de mangueiras de incêndio .', true, 0, '/products/uniao-storz-para-mangueira-de-incendio.png'),
('REGISTRO DE GAVETA BRUTO', 'Combate a Incêndio', 'Registro de gaveta bruto para sistemas de combate a incêndio .', true, 0, '/products/registro-de-gaveta-bruto.png'),
('REGISTRO GLOBO ANGULAR PN16 220 LBS', 'Combate a Incêndio', 'Registro globo angular PN16 220 LBS.', true, 0, '/products/registro-globo-angular-pn16-220-lbs.png'),
('ESGUICHO REGULÁVEL EM LATÃO 1.1/2"', 'Combate a Incêndio', 'Esguicho regulável em latão 1.1/2".', true, 0, '/products/esguicho-regulavel-em-latao-1-1-2.png'),
('ESGUICHO REGULÁVEL EM LATÃO 2.1/2"', 'Combate a Incêndio', 'Esguicho regulável em latão 2.1/2".', true, 0, '/products/esguicho-regulavel-em-latao-2-1-2.png'),
('TAMPÃO STORZ COM CORRENTE', 'Combate a Incêndio', 'Tampão Storz com corrente para proteção de conexões .', true, 0, '/products/tampao-storz-com-corrente.png'),
('REGISTRO GLOBO ANGULAR PN10 120 LBS', 'Combate a Incêndio', 'Registro globo angular PN10 120 LBS.', true, 0, '/products/registro-globo-angular-pn10-120-lbs.png'),
('CHAVE STORZ DUPLA', 'Combate a Incêndio', 'Chave Storz dupla para abertura / fechamento de conexões .', true, 0, '/products/chave-storz-dupla.png'),
('MANÔMETRO GLICERINA', 'Acessórios', 'Manômetro com glicerina para amortecimento de vibrações .', true, 0, '/products/manometro-glicerina.png'),
('TAMPA DE FERRO FUNDIDO PARA RECALQUE DE INCÊNDIO', 'Acessórios', 'Tampa de ferro fundido para recalque de incêndio .', true, 0, '/products/tampa-de-ferro-fundido-para-recalque-de-incendio.png'),
('MANGUEIRA DE INCÊNDIO TIPO 1 - 1.1/2" - 15 METROS', 'Mangueira', 'Mangueira de incêndio tipo 1, 1.1/2", 15 metros.', true, 0, '/products/mangueira-de-incendio-tipo-1-1-1-2-15-metros.png'),
('MANGUEIRA DE INCÊNDIO TIPO 1 - 1.1/2" - 20 METROS', 'Mangueira', 'Mangueira de incêndio tipo 1, 1.1/2", 20 metros.', true, 0, '/products/mangueira-de-incendio-tipo-1-1-1-2-20-metros.png'),
('MANGUEIRA DE INCÊNDIO TIPO 2 - 1.1/2" - 15 METROS', 'Mangueira', 'Mangueira de incêndio tipo 2, 1.1/2", 15 metros.', true, 0, '/products/mangueira-de-incendio-tipo-2-1-1-2-15-metros.png'),
('MANGUEIRA DE INCÊNDIO TIPO 2 - 1.1/2" - 20 METROS', 'Mangueira', 'Mangueira de incêndio tipo 2, 1.1/2", 20 metros.', true, 0, '/products/mangueira-de-incendio-tipo-2-1-1-2-20-metros.png'),
('ABRIGO PARA HIDRANTE E EXTINTORES', 'Extintor', 'Abrigo para proteção e sinalização de hidrantes e extintores .', true, 0, '/products/abrigo-para-hidrante-e-extintores.png'),
('ACIONADOR MANUAL', 'Alarme', 'Acionador manual para sistemas de alarme de incêndio .', true, 0, '/products/acionador-manual.png'),
('SINALIZADOR AUDIOVISUAL', 'Acessórios', 'Sinalizador audiovisual para alarmes de incêndio .', true, 0, '/products/sinalizador-audiovisual.png'),
('DETECTOR DE TEMPERATURA', 'Alarme', 'Detector de temperatura para sistemas de detecção de incêndio .', true, 0, '/products/detector-de-temperatura.png'),
('CENTRAL DE ALARME - 12 SETORES CONVENCIONAL', 'Alarme', 'Central de alarme convencional com 12 setores .', true, 0, '/products/central-de-alarme-12-setores-convencional.png'),
('CENTRAL DE ALARME - 24 SETORES CONVENCIONAL', 'Alarme', 'Central de alarme convencional com 24 setores .', true, 0, '/products/central-de-alarme-24-setores-convencional.png'),
('CENTRAL DE ALARME - ENDEREÇÁVEL', 'Alarme', 'Central de alarme endereçável para sistemas de detecção .', true, 0, '/products/central-de-alarme-enderecavel.png'),
('DETECTOR DE FUMAÇA', 'Alarme', 'Detector de fumaça para sistemas de alarme de incêndio .', true, 0, '/products/detector-de-fumaca.png'),
('ACIONADOR DE BOMBA', 'Alarme', 'Acionador de bomba para sistemas de combate a incêndio .', true, 0, '/products/acionador-de-bomba.png'),
('ANEL DE COBRE PARA EMPATE DE MANGUEIRA DE INCÊNDIO', 'Mangueira', 'Anel de cobre para empate de mangueira de incêndio .', true, 0, '/products/anel-de-cobre-para-empate-de-mangueira-de-incendio.png'),
('PORTA CORTA-FOGO P90 2100 X 890MM', 'Acessórios', 'Porta corta-fogo P90, dimensões 2100 x 890mm.', true, 0, '/products/porta-corta-fogo-p90-2100-x-890mm.png'),
('PORTA CORTA-FOGO P90 2100 X 1180MM', 'Acessórios', 'Porta corta-fogo P90, dimensões 2100 x 1180mm.', true, 0, '/products/porta-corta-fogo-p90-2100-x-1180mm.png'),
('LUMINÁRIA 30 LEDS', 'Iluminação', 'Luminária de emergência com 30 LEDs.', true, 0, '/products/luminaria-30-leds.png'),
('LUMINÁRIA BLOCO FAROLETE 2.200 LÚMENS', 'Iluminação', 'Luminária bloco farolete com 2.200 lúmens .', true, 0, '/products/luminaria-bloco-farolete-2-200-lumens.png'),
('LUMINÁRIA BLOCO FAROLETE 1.200 LÚMENS', 'Iluminação', 'Luminária bloco farolete com 1.200 lúmens .', true, 0, '/products/luminaria-bloco-farolete-1-200-lumens.png'),
('BALIZAMENTO DE SAÍDA DE EMERGÊNCIA', 'Iluminação', 'Balizamento para sinalização de saída de emergência .', true, 0, '/products/balizamento-de-saida-de-emergencia.png'),
('FITA DE DEMARCAÇÃO DE SOLO AMARELA', 'Fitas', 'Fita de demarcação de solo na cor amarela .', true, 0, '/products/fita-de-demarcacao-de-solo-amarela.png'),
('FITA DE DEMARCAÇÃO DE SOLO PRETA', 'Fitas', 'Fita de demarcação de solo na cor preta .', true, 0, '/products/fita-de-demarcacao-de-solo-preta.png'),
('FITA ANTIDERRAPANTE PRETA', 'Fitas', 'Fita antiderrapante na cor preta .', true, 0, '/products/fita-antiderrapante-preta.png'),
('FITA DE DEMARCAÇÃO DE SOLO VERMELHA', 'Fitas', 'Fita de demarcação de solo na cor vermelha .', true, 0, '/products/fita-de-demarcacao-de-solo-vermelha.png'),
('FITA ANTIDERRAPANTE ZEBRADA', 'Fitas', 'Fita antiderrapante com padrão zebrado.', true, 0, '/products/fita-antiderrapante-zebrada.png')
ON CONFLICT (name) DO UPDATE SET 
  image_url = EXCLUDED.image_url,
  description = EXCLUDED.description,
  type = EXCLUDED.type;
