-- Migration: 007_add_complete_product_catalog.sql
-- Catálogo atualizado conforme documento DOCX

INSERT INTO public.products (name, type, description, in_stock, price, image_url)
SELECT name, type, description, in_stock, price, image_url FROM (VALUES
('Extintor Pó Químico BC - 8 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 8 Kg. Capacidade : 30 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-8-kg.png'),
('Extintor Pó Químico BC - 6 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 6 Kg. Capacidade : 20 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-6-kg.png'),
('Extintor Pó Químico BC - 50 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 50 Kg. Capacidade : 80 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-bc-50-kg.png'),
('Extintor CO² BC - 6 Kg', 'Extintor', 'Agente Químico : CO². Carga: 6 Kg. Capacidade : 5 B:C. Classe de fogo : B:C. Garantia : 1 Ano.', true, 0, '/products/extintor-co-bc-6-kg.png'),
('Extintor Água Classe A - 10 L', 'Extintor', 'Agente Químico : ÁGUA. Carga: 10 L. Capacidade : 2 A. Classe de fogo : A. Garantia : 1 Ano.', true, 0, '/products/extintor-agua-classe-a-10-l.png'),
('Extintor Espuma Mecânica AB - 10 L', 'Extintor', 'Agente Químico : ESPUMA MECÂNICA. Carga: 10 L. Capacidade : 2 A. Classe de fogo : A. Garantia : 1 Ano.', true, 0, '/products/extintor-espuma-mecanica-ab-10-l.png'),
('Extintor Pó Químico ABC - 0,900 Kg (FIAT)', 'Extintor', 'Agente Químico : PQS. Carga: 0,900 Kg. Capacidade : 1 A - 5 B:C. Classe de fogo : ABC. Garantia : 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-0-900-kg-fiat.png'),
('Extintor Pó Químico ABC - 2 Kg (1A-10BC)', 'Extintor', 'Agente Químico : PQS. Carga: 2 Kg. Capacidade : 1 A - 10 B:C. Classe de fogo : ABC. Garantia : 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-2-kg-1a-10bc.png'),
('Extintor Pó Químico ABC - 2 Kg (2A-20BC)', 'Extintor', 'Agente Químico : PQS. Carga: 2 Kg. Capacidade : 2 A - 20 B:C. Classe de fogo : ABC. Garantia : 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-2-kg-2a-20bc.png'),
('Extintor Pó Químico ABC - 4 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 4 Kg. Capacidade : 2 A - 20 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-4-kg.png'),
('Extintor Pó Químico ABC - 6 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 6 Kg. Capacidade : 4 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-6-kg.png'),
('Extintor Pó Químico ABC - 12 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 12 Kg. Capacidade : 6 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 | 3 | 5 Anos.', true, 0, '/products/extintor-po-quimico-abc-12-kg.png'),
('Extintor Pó Químico ABC - 20 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 20 Kg. Capacidade : 6 A - 40 B:C. Classe de fogo : ABC. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-abc-20-kg.png'),
('Extintor Pó Químico ABC - 30 Kg', 'Extintor', 'Agente Químico : PQS. Carga: 30 Kg. Capacidade : 6 A - 80 B:C. Classe de fogo : ABC. Garantia : 1 Ano.', true, 0, '/products/extintor-po-quimico-abc-30-kg.png'),
('Pó Químico BC - Bicarbonato de Sódio 95%', 'Agente Extintor', 'Agente Químico : Bicarbonato de Sódio 95%. Embalagem : 50 Kg.', true, 0, '/products/po-quimico-bc-bicarbonato-de-sodio-95.png'),
('Válvula M30 Completa', 'Componentes', 'Código: 85281. Válvula completa para extintores de baixa pressão .', true, 0, '/products/valvula-m30-completa.png'),
('Pera M30', 'Acessórios', 'Código: 504 | 68031. Pera para válvula M30.', true, 0, '/products/pera-m30.png'),
('Manômetro 1.0 - Caixa Inox', 'Acessórios', 'Código: 85271. Manômetro com caixa em inox.', true, 0, '/products/manometro-1-0-caixa-inox.png'),
('Mola Curta (Altura 1,98 cm)', 'Acessórios', 'Código: 3109. Mola curta para válvulas .', true, 0, '/products/mola-curta-altura-1-98-cm.png'),
('Válvula M22', 'Componentes', 'Código: 85881. Válvula M22 para extintores .', true, 0, '/products/valvula-m22.png'),
('Oring Grossa 26x4 mm para Válvula M30', 'Componentes', 'Código: 85341. Oring grossa para vedação de válvula M30.', true, 0, '/products/oring-grossa-26x4-mm-para-valvula-m30.png'),
('Manômetro 1.4 Inox', 'Acessórios', 'Código: 3139. Manômetro com escala 1.4 e caixa inox.', true, 0, '/products/manometro-1-4-inox.png'),
('Pino Completo para Válvula M30', 'Componentes', 'Código: 3105. Pino completo para válvula M30 ( arruela em latão + pera + oring de pino ). Medida : 33 mm.', true, 0, '/products/pino-completo-para-valvula-m30.png'),
('Mola Longa (Altura 4,3 cm)', 'Acessórios', 'Código: 5776. Mola longa para válvulas .', true, 0, '/products/mola-longa-altura-4-3-cm.png'),
('Cordão para Válvula M30', 'Componentes', 'Código: 73341. Cordão de segurança para válvula M30.', true, 0, '/products/cordao-para-valvula-m30.png'),
('Trava para Válvula M30', 'Componentes', 'Código: 4357. Trava de segurança para válvula M30.', true, 0, '/products/trava-para-valvula-m30.png'),
('Mangueira para Extintor P4/P6/P8 - 500 mm', 'Extintor', 'Código: 85631. Mangueira para extintores P4, P6 e P8 com 500 mm.', true, 0, '/products/mangueira-para-extintor-p4-p6-p8-500-mm.png'),
('Mangueira para Extintor P12 - 600 mm', 'Extintor', 'Código: 49. Mangueira para extintor P12 com 600 mm.', true, 0, '/products/mangueira-para-extintor-p12-600-mm.png'),
('Mangueira para Extintor AP10L - 600 mm', 'Extintor', 'Código: 85641. Mangueira para extintor AP10L com 600 mm.', true, 0, '/products/mangueira-para-extintor-ap10l-600-mm.png'),
('Sifão Plástico para Extintor P4 - 11 mm', 'Extintor', 'Código: 85581. Sifão plástico para extintor P4, 11 mm.', true, 0, '/products/sifao-plastico-para-extintor-p4-11-mm.png'),
('Sifão Plástico para Extintor P6 - 460 mm', 'Extintor', 'Código: 85591. Sifão plástico para extintor P6, 460 mm.', true, 0, '/products/sifao-plastico-para-extintor-p6-460-mm.png'),
('Sifão Plástico para Extintor P8 - 380 mm', 'Extintor', '', true, 0, '/products/sifao-plastico-para-extintor-p8-380-mm.png'),
('Sifão Plástico para Extintor P12/AP10L - 535 mm', 'Extintor', 'Código: 85611. Sifão plástico para extintores P12 e AP10L, 535 mm.', true, 0, '/products/sifao-plastico-para-extintor-p12-ap10l-535-mm.png'),
('Capa para Extintores', 'Extintor', 'Capa protetora para todos os tamanhos de extintores .', true, 0, '/products/capa-para-extintores.png'),
('Mangueira de Incêndio - Tipo 1, 2 e 3', 'Mangueira', 'Mangueiras de incêndio tipos 1, 2 e 3. Tamanhos : 15, 20, 25 e 30 metros.', true, 0, '/products/mangueira-de-incendio-tipo-1-2-e-3.png'),
('Conjunto APAG para CO ²', 'Acessórios', 'Código: 279. Conjunto completo para extintores CO².', true, 0, '/products/conjunto-apag-para-co.png'),
('Mangueira CO²', 'Mangueira', 'Código: 53. Mangueira específica para extintores CO².', true, 0, '/products/mangueira-co.png'),
('Difusor para CO ² Completo', 'Acessórios', 'Código: 4341. Difusor completo para extintores CO².', true, 0, '/products/difusor-para-co-completo.png'),
('Punho para CO ²', 'Acessórios', 'Código: 534. Punho para extintores CO².', true, 0, '/products/punho-para-co.png'),
('Quebra Jato para CO ²', 'Acessórios', 'Código: 535. Quebra jato para extintores CO².', true, 0, '/products/quebra-jato-para-co.png'),
('Válvula para CO ² Completa', 'Componentes', 'Código: 479. Válvula completa para extintores CO².', true, 0, '/products/valvula-para-co-completa.png'),
('Sifão para Extintor CO² - 4 Kg', 'Extintor', 'Código: 365. Sifão para extintor CO² de 4 kg.', true, 0, '/products/sifao-para-extintor-co-4-kg.png'),
('Sifão para Extintor CO² - 6 Kg', 'Extintor', 'Código: 368. Sifão para extintor CO² de 6 kg.', true, 0, '/products/sifao-para-extintor-co-6-kg.png'),
('Sifão para Extintor CO² - 10 Kg', 'Extintor', 'Código: 364. Sifão para extintor CO² de 10 kg.', true, 0, '/products/sifao-para-extintor-co-10-kg.png'),
('Válvula Abertura Lenta CO²', 'Componentes', 'Código: 1833. Válvula de abertura lenta para extintores CO².', true, 0, '/products/valvula-abertura-lenta-co.png'),
('Válvula M30 Completa ( Espuma Mecânica )', 'Componentes', 'Código: 85281. Válvula completa para extintores de espuma mecânica 10L.', true, 0, '/products/valvula-m30-completa-espuma-mecanica.png'),
('Manômetro 1.0 - Caixa Inox ( Espuma Mecânica )', 'Acessórios', 'Código: 85271. Manômetro com caixa inox para extintores de espuma .', true, 0, '/products/manometro-1-0-caixa-inox-espuma-mecanica.png'),
('Mangueira de Espuma Mecânica 600 mm com Difusor', 'Mangueira', 'Código: 89331. Mangueira para extintor de espuma mecânica com difusor .', true, 0, '/products/mangueira-de-espuma-mecanica-600-mm-com-difusor.png'),
('Líquido Gerador de Espuma - LGE 3%', 'Acessórios', 'Código: 1429. Líquido gerador de espuma a 3%.', true, 0, '/products/liquido-gerador-de-espuma-lge-3.png'),
('Líquido Gerador de Espuma - LGE 6%', 'Acessórios', 'Código: 1697. Líquido gerador de espuma a 6%.', true, 0, '/products/liquido-gerador-de-espuma-lge-6.png'),
('Líquido Gerador de Espuma - LGE 3%-6%', 'Acessórios', 'Código: 4849. Líquido gerador de espuma versátil 3%-6%.', true, 0, '/products/liquido-gerador-de-espuma-lge-3-6.png'),
('Manômetro 1.0 - Caixa Inox (P2 ABC)', 'Acessórios', 'Código: 85271. Manômetro para extintores P2 ABC.', true, 0, '/products/manometro-1-0-caixa-inox-p2-abc.png'),
('Válvula M-22 com Rosca (P2 ABC)', 'Componentes', 'Código: 85881. Válvula M22 com rosca para P2 ABC.', true, 0, '/products/valvula-m-22-com-rosca-p2-abc.png'),
('Mangueira P2 ABC', 'Mangueira', 'Código: 61091. Mangueira específica para extintores P2 ABC.', true, 0, '/products/mangueira-p2-abc.png'),
('Válvula M38 para Carreta - PQS 20 Kg', 'Componentes', 'Código: 85551. Válvula M38 para extintor sobre rodas de 20 kg.', true, 0, '/products/valvula-m38-para-carreta-pqs-20-kg.png'),
('Válvula M38 para Carreta - PQS 30 Kg', 'Componentes', 'Código: 85561. Válvula M38 para extintor sobre rodas de 30 kg.', true, 0, '/products/valvula-m38-para-carreta-pqs-30-kg.png'),
('Válvula M38 para Carreta - PQS 50 Kg', 'Componentes', 'Código: 85571. Válvula M38 para extintor sobre rodas de 50 kg.', true, 0, '/products/valvula-m38-para-carreta-pqs-50-kg.png'),
('Mangueira para Extintor Carreta 30 Kg', 'Extintor', 'Código: 5068. Mangueira para extintor sobre rodas de 30 kg.', true, 0, '/products/mangueira-para-extintor-carreta-30-kg.png'),
('Mangueira P20 - 3 metros', 'Mangueira', 'Código: 85401. Mangueira de 3 metros para extintor de 20 kg.', true, 0, '/products/mangueira-p20-3-metros.png'),
('Mangueira para Extintor Carreta 50 Kg', 'Extintor', 'Código: 90971. Mangueira para extintor sobre rodas de 50 kg.', true, 0, '/products/mangueira-para-extintor-carreta-50-kg.png'),
('Pistola de Carreta - 20 Kg', 'Acessórios', 'Código: 85411. Pistola para extintor sobre rodas de 20 kg.', true, 0, '/products/pistola-de-carreta-20-kg.png'),
('Adaptador Carreta - PQS 30/50 Kg', 'Acessórios', 'Código: 5618. Adaptador para carretas de 30 kg e 50 kg.', true, 0, '/products/adaptador-carreta-pqs-30-50-kg.png'),
('Roda Plástica PQS 20 Kg', 'Acessórios', 'Código: 85421. Roda plástica para extintor sobre rodas de 20 kg.', true, 0, '/products/roda-plastica-pqs-20-kg.png'),
('Suporte Veicular - Modelo FIAT', 'Suporte', 'Código: 457. Suporte para extintor veicular modelo FIAT.', true, 0, '/products/suporte-veicular-modelo-fiat.png'),
('Suporte Veicular - Modelo Universal', 'Suporte', 'Código: 4459. Suporte para extintor veicular modelo universal.', true, 0, '/products/suporte-veicular-modelo-universal.png'),
('Suporte Veicular - Modelo P2 ABC', 'Suporte', 'Código: 461. Suporte veicular para extintor P2 ABC.', true, 0, '/products/suporte-veicular-modelo-p2-abc.png'),
('Suporte Veicular - Modelo P4/P6', 'Suporte', 'Código: 4355. Suporte veicular para extintores P4 e P6.', true, 0, '/products/suporte-veicular-modelo-p4-p6.png'),
('Suporte Veicular - Modelo P8/P12', 'Suporte', 'Código: 456. Suporte veicular para extintores P8 e P12.', true, 0, '/products/suporte-veicular-modelo-p8-p12.png'),
('Suporte Parede', 'Suporte', 'Código: 1725. Suporte de parede para extintores .', true, 0, '/products/suporte-parede.png'),
('Suporte Tripé Desmontável - P4/P6', 'Suporte', 'Código: 65461. Suporte tripé desmontável para extintores P4 e P6.', true, 0, '/products/suporte-tripe-desmontavel-p4-p6.png'),
('Suporte Tripé Desmontável - P8/P12/AP10', 'Suporte', 'Código: 65471. Suporte tripé desmontável para extintores P8, P12 e AP10.', true, 0, '/products/suporte-tripe-desmontavel-p8-p12-ap10.png'),
('Suporte Tripé - P4/P6', 'Suporte', 'Código: 450. Suporte tripé fixo para extintores P4 e P6.', true, 0, '/products/suporte-tripe-p4-p6.png'),
('Suporte Tripé - P8/P12/AP10', 'Suporte', 'Código: 454. Suporte tripé fixo para extintores P8, P12 e AP10.', true, 0, '/products/suporte-tripe-p8-p12-ap10.png'),
('Suporte Tripé com Haste - P4/P6', 'Suporte', 'Código: 676. Suporte tripé com haste para extintores P4 e P6.', true, 0, '/products/suporte-tripe-com-haste-p4-p6.png'),
('Suporte Tripé com Haste - P8/P12/AP10', 'Suporte', 'Código: 702. Suporte tripé com haste para extintores P8, P12 e AP10.', true, 0, '/products/suporte-tripe-com-haste-p8-p12-ap10.png'),
('Suporte Solo Tripé Bicromatizado - P4/P6', 'Suporte', 'Código: 2962. Suporte solo tripé bicromatizado com fixação no solo para P4/P6.', true, 0, '/products/suporte-solo-tripe-bicromatizado-p4-p6.png'),
('Suporte Solo Tripé Bicromatizado - P8/P12/AP10', 'Suporte', 'Código: 64631. Suporte solo tripé bicromatizado com fixação no solo para P8/P12/AP10.', true, 0, '/products/suporte-solo-tripe-bicromatizado-p8-p12-ap10.png'),
('Suporte Solo Tripé Bicromatizado - CO²', 'Suporte', 'Código: 64631. Suporte solo tripé bicromatizado com fixação no solo para CO ².', true, 0, '/products/suporte-solo-tripe-bicromatizado-co.png'),
('Suporte Solo Tripé Cromado - P4/P6', 'Suporte', 'Código: 1039. Suporte solo tripé cromado para P4/P6.', true, 0, '/products/suporte-solo-tripe-cromado-p4-p6.png'),
('Suporte Solo Tripé Cromado - P8/P12/AP10', 'Suporte', 'Código: 1035. Suporte solo tripé cromado para P8/P12/AP10.', true, 0, '/products/suporte-solo-tripe-cromado-p8-p12-ap10.png'),
('Suporte Solo Tripé Cromado - CO²', 'Suporte', 'Código: 1035. Suporte solo tripé cromado para CO ².', true, 0, '/products/suporte-solo-tripe-cromado-co.png'),
('Suporte de Solo Tripé Desmontável de Polietileno - P8/P12/AP/EM', 'Suporte', 'Código: 77471. Suporte solo tripé desmontável de polietileno de alta densidade para P8/P12/AP/EM.', true, 0, '/products/suporte-de-solo-tripe-desmontavel-de-polietileno-p8-p12-ap-em.png'),
('Suporte de Solo Tripé Desmontável de Polietileno - CO²', 'Suporte', 'Código: 77471. Suporte solo tripé desmontável de polietileno de alta densidade para CO ².', true, 0, '/products/suporte-de-solo-tripe-desmontavel-de-polietileno-co.png'),
('Suporte de Solo Batom - P4/P6', 'Suporte', 'Código: 88671. Suporte de solo tipo " batom " para P4/P6.', true, 0, '/products/suporte-de-solo-batom-p4-p6.png'),
('Suporte de Solo Batom - P8/P12/AP/EM', 'Suporte', 'Código: 3900. Suporte de solo tipo " batom " para P8/P12/AP/EM.', true, 0, '/products/suporte-de-solo-batom-p8-p12-ap-em.png'),
('Suporte de Solo Batom - CO²', 'Suporte', 'Código: 3900. Suporte de solo tipo " batom " para CO ².', true, 0, '/products/suporte-de-solo-batom-co.png'),
('Haste para Suporte Tripé', 'Suporte', 'Código: 69961. Haste para suporte tripé (P4/P6/P8/P12/AP/EM/10L/CO²).', true, 0, '/products/haste-para-suporte-tripe.png'),
('Adaptador Storz 2.1/2" X 1.1/2"', 'Combate a Incêndio', 'Adaptador Storz 2.1/2" x 1.1/2". Opção Latão ou Alumínio .', true, 0, '/products/adaptador-storz-2-1-2-x-1-1-2.png'),
('Redutor Storz 2.1/2" X 1.1/2"', 'Combate a Incêndio', 'Redutor Storz 2.1/2" x 1.1/2". Opção Latão ou Alumínio .', true, 0, '/products/redutor-storz-2-1-2-x-1-1-2.png'),
('União Storz para Mangueira de Incêndio', 'Mangueira', 'União Storz para conexão de mangueiras de incêndio .', true, 0, '/products/uniao-storz-para-mangueira-de-incendio.png'),
('Registro de Gaveta Bruto', 'Combate a Incêndio', 'Registro de gaveta bruto para sistemas de combate a incêndio .', true, 0, '/products/registro-de-gaveta-bruto.png'),
('Registro Globo Angular PN16 220 LBS', 'Combate a Incêndio', 'Registro globo angular PN16 220 LBS.', true, 0, '/products/registro-globo-angular-pn16-220-lbs.png'),
('Esguicho Regulável em Latão 1.1/2"', 'Combate a Incêndio', 'Esguicho regulável em latão 1.1/2".', true, 0, '/products/esguicho-regulavel-em-latao-1-1-2.png'),
('Esguicho Regulável em Latão 2.1/2"', 'Combate a Incêndio', 'Esguicho regulável em latão 2.1/2".', true, 0, '/products/esguicho-regulavel-em-latao-2-1-2.png'),
('Tampão Storz com Corrente', 'Combate a Incêndio', 'Tampão Storz com corrente para proteção de conexões .', true, 0, '/products/tampao-storz-com-corrente.png'),
('Registro Globo Angular PN10 120 LBS', 'Combate a Incêndio', 'Registro globo angular PN10 120 LBS.', true, 0, '/products/registro-globo-angular-pn10-120-lbs.png'),
('Chave Storz Dupla', 'Combate a Incêndio', 'Chave Storz dupla para abertura / fechamento de conexões .', true, 0, '/products/chave-storz-dupla.png'),
('Manômetro Glicerina', 'Acessórios', 'Manômetro com glicerina para amortecimento de vibrações .', true, 0, '/products/manometro-glicerina.png'),
('Tampa de Ferro Fundido para Recalque de Incêndio', 'Acessórios', 'Tampa de ferro fundido para recalque de incêndio .', true, 0, '/products/tampa-de-ferro-fundido-para-recalque-de-incendio.png'),
('Mangueira de Incêndio Tipo 1 - 1.1/2" - 15 Metros', 'Mangueira', 'Mangueira de incêndio tipo 1, 1.1/2", 15 metros.', true, 0, '/products/mangueira-de-incendio-tipo-1-1-1-2-15-metros.png'),
('Mangueira de Incêndio Tipo 1 - 1.1/2" - 20 Metros', 'Mangueira', 'Mangueira de incêndio tipo 1, 1.1/2", 20 metros.', true, 0, '/products/mangueira-de-incendio-tipo-1-1-1-2-20-metros.png'),
('Mangueira de Incêndio Tipo 2 - 1.1/2" - 15 Metros', 'Mangueira', 'Mangueira de incêndio tipo 2, 1.1/2", 15 metros.', true, 0, '/products/mangueira-de-incendio-tipo-2-1-1-2-15-metros.png'),
('Mangueira de Incêndio Tipo 2 - 1.1/2" - 20 Metros', 'Mangueira', 'Mangueira de incêndio tipo 2, 1.1/2", 20 metros.', true, 0, '/products/mangueira-de-incendio-tipo-2-1-1-2-20-metros.png'),
('Abrigo para Hidrante e Extintores', 'Extintor', 'Abrigo para proteção e sinalização de hidrantes e extintores .', true, 0, '/products/abrigo-para-hidrante-e-extintores.png'),
('Sinalizador Audiovisual', 'Acessórios', 'Sinalizador audiovisual para alarmes de incêndio .', true, 0, '/products/sinalizador-audiovisual.png'),
('Detector de Temperatura', 'Acessórios', 'Detector de temperatura para sistemas de detecção de incêndio .', true, 0, '/products/detector-de-temperatura.png'),
('Central de Alarme - 12 Setores Convencional', 'Acessórios', 'Central de alarme convencional com 12 setores .', true, 0, '/products/central-de-alarme-12-setores-convencional.png'),
('Central de Alarme - 24 Setores Convencional', 'Acessórios', 'Central de alarme convencional com 24 setores .', true, 0, '/products/central-de-alarme-24-setores-convencional.png'),
('Central de Alarme - Endereçável', 'Acessórios', 'Central de alarme endereçável para sistemas de detecção .', true, 0, '/products/central-de-alarme-enderecavel.png'),
('Detector de Fumaça', 'Acessórios', 'Detector de fumaça para sistemas de alarme de incêndio .', true, 0, '/products/detector-de-fumaca.png'),
('Acionador de Bomba', 'Acessórios', 'Acionador de bomba para sistemas de combate a incêndio .', true, 0, '/products/acionador-de-bomba.png'),
('Anel de Cobre para Empate de Mangueira de Incêndio', 'Mangueira', 'Anel de cobre para empate de mangueira de incêndio .', true, 0, '/products/anel-de-cobre-para-empate-de-mangueira-de-incendio.png'),
('Porta Corta-Fogo P90 2100 x 890mm', 'Acessórios', 'Porta corta-fogo P90, dimensões 2100 x 890mm.', true, 0, '/products/porta-corta-fogo-p90-2100-x-890mm.png'),
('Porta Corta-Fogo P90 2100 x 1180mm', 'Acessórios', 'Porta corta-fogo P90, dimensões 2100 x 1180mm.', true, 0, '/products/porta-corta-fogo-p90-2100-x-1180mm.png'),
('Luminária 30 LEDs', 'Iluminação', 'Luminária de emergência com 30 LEDs.', true, 0, '/products/luminaria-30-leds.png'),
('Luminária Bloco Farolete 2.200 Lúmens', 'Iluminação', 'Luminária bloco farolete com 2.200 lúmens .', true, 0, '/products/luminaria-bloco-farolete-2-200-lumens.png'),
('Luminária Bloco Farolete 1.200 Lúmens', 'Iluminação', 'Luminária bloco farolete com 1.200 lúmens .', true, 0, '/products/luminaria-bloco-farolete-1-200-lumens.png'),
('Balizamento de Saída de Emergência', 'Iluminação', 'Balizamento para sinalização de saída de emergência .', true, 0, '/products/balizamento-de-saida-de-emergencia.png'),
('Fita de Demarcação de Solo Amarela', 'Fitas', 'Fita de demarcação de solo na cor amarela .', true, 0, '/products/fita-de-demarcacao-de-solo-amarela.png'),
('Fita de Demarcação de Solo Preta', 'Fitas', 'Fita de demarcação de solo na cor preta .', true, 0, '/products/fita-de-demarcacao-de-solo-preta.png'),
('Fita Antiderrapante Preta', 'Fitas', 'Fita antiderrapante na cor preta .', true, 0, '/products/fita-antiderrapante-preta.png'),
('Fita de Demarcação de Solo Vermelha', 'Fitas', 'Fita de demarcação de solo na cor vermelha .', true, 0, '/products/fita-de-demarcacao-de-solo-vermelha.png'),
('Fita Antiderrapante Zebrada', 'Fitas', 'Fita antiderrapante com padrão zebrado.', true, 0, '/products/fita-antiderrapante-zebrada.png')
) AS t (name, type, description, in_stock, price, image_url)
WHERE NOT EXISTS (
    SELECT 1 FROM public.products p WHERE p.name = t.name
);
